### ISSUE TITLE
Add support for multiple formats

### ISSUE THREAD

**Issue by ozasadnyy** [mlisook/plastic-image#11]
[Webp](https://developers.google.com/speed/webp/) is amazing image format but unfortunately, not all browsers support it. The combination of webp + lazy loading should be super awesome!

**Comment by mlisook** [comment]
Hi, thanks for the suggestion.

What are you thinking as far as how it would work?  Maybe something like:

- If the browser supports webp _and_ there is at least 1 webp image in the srcset
  - discard the non webp images
- else
  - discard the webp images

or ??

**Comment by ozasadnyy** [comment]
Here are 3 basic techniques: https://developers.google.com/speed/webp/faq
* Modernizr
* HTML5 <picture> element
* In your own JavaScript

I am more for second way

**Comment by mlisook** [comment]
Well, this control extends `iron-image` which not only doesn't use the `<picture>` element, but doesn't even really use the `<img>` element - it actually sets the background image of a `<div>` in its shadow dom.

I would think it would be necessary to detect support for webp in JavaScript.

So, if there are _any_ webp images in the `srcset`, and webp is supported, do we assume the user wants to serve one of those in preference to any of the JPG or PNGs?

**Comment by ozasadnyy** [comment]
Correct. These files are much smaller

**Comment by mlisook** [comment]
I like your idea and it is easy enough to implement.  Look for an enhancement to do this in the next couple of days.

Thank you!

**Comment by mlisook** [comment]
Support for webp has been added in [PR #13 Add Webp Support](https://github.com/mlisook/plastic-image/pull/13).  Readme documentation has been updated to reflect the new feature.  New version is tagged 1.0.4.
