### ISSUE TITLE
webp url regex incorrectly assumes all webp urls end with .webp (so it fails e.g. if there are any query params)

### ISSUE THREAD

**Issue by jab** [mlisook/plastic-image#38]
It looks like the webp regex only matches webp image urls that end with `.webp` ([src](https://github.com/mlisook/plastic-image/blob/a850661abd8653d80750ae3a7844fa119d336115/plastic-image.html#L190-L192)):
```javascript
_webpRegex: {
  type: RegExp,
  value: /.+\.webp$/i    // note the `$`
},
```

But this fails to match valid webp image urls like `example.com/image.webp?v=1` or even `example.com/image.webp?`.

<details><summary><em>(click for aside)</em></summary>
<sub>Technically, the filename extension part of a url isn't even what determines the filetype, rather the mimetype specified in the `Content-Type` header of the response does. So even a url like `example.com/avatar` with no extension may very well be a webp image. In many cases, this is even the best design, e.g. when the requester doesn't / shouldn't need to know what the image type is, and only expects that there's <em>some</em> image at the requested path, letting the server tell it what the type is (possibly generated / decided dynamically). This design is less common than query params, and maybe more complex to support, in which case this may bear considering separately.)</sub>
</details><br>

You could drop the `$` from the regex, but that would result in false positives like `/v2.webplatform.gif`. You could instead strip off any query string before testing against the regex, but let's back up a second.

There's no reason `<plastic-image>`’s webp detection needs to trade implicit magic for robustness. The `<plastic-image>` API could simply let users explicitly tell the element what webp url regex to use, so `<plastic-image>` doesn't have to either assume one size fits all, or do any additional url sniffing guesswork.

Then, users have the flexibility to override the default regex in whatever way they need. e.g. A user may have no control over the filename extension in the url, and may only be able to indicate that a webp image is expected by adding (what would otherwise be a no-op) `webp=1` query param. In that case, the user could just append that query param to all their webp urls, specify the corresponding regex, and get perfect detection, e.g.
```html
<plastic-image webp-url-regex="webp=1" srcset="/user/avatar/v3?webp=1, /user/fallback.png" ...>
```
What do you think?

Hope this helps, and thank you for the great work on `<plastic-image>`!

**Comment by mlisook** [comment]
Thank you for reporting this issue.

I really like your suggestion of allowing an override to the webp regex.  It'll be quite straightforward to implement and document, so expect a new release sometime tomorrow.

**Comment by mlisook** [comment]
I've merged in a change, PR #39 , which adds the `webpRegex` property as a way to override the default regex, updated the readme to reflect that and added a couple of basic tests in test/webp.html

The new release is 1.0.14

**Comment by jab** [comment]
Tested the new web-regex API and looks like it's working great. Thanks for the quick fix and release!

**Comment by mlisook** [comment]
No problem.  Thanks again for reporting the issue and a great way to fix it.
