### ISSUE TITLE
importPath is undefined

### ISSUE THREAD

**Issue by elarb** [mlisook/plastic-image#42]
Currently the `importPath` is used for the source of the polyfill script (needed for e.g. IE 11), but it seems to be undefined, causing the client to request `undefinedintersection-observer.js`. It might have to do with a missing `<dom-module>` wrapper in the element definition, as discussed in Polymer/docs/issues/2466.

**Comment by mlisook** [comment]
Thank you for reporting this.

May I ask what version number of this element, and what Polymer version you are using.

**Comment by elarb** [comment]
I am using version `3.0.0` of this element and `3.0.2` of Polymer

**Comment by mlisook** [comment]
Thank you, I'll investigate immediately.

**Comment by mlisook** [comment]
I've merged PR #43 to address this.  I had not included a static getter that is required if using importPath as described in the [Polymer 3.0 upgrade guide](https://www.polymer-project.org/3.0/docs/upgrade)

I've also published the update to NPM - version 3.0.2

Thanks again for finding and reporting this issue.

**Comment by elarb** [comment]
Thanks, that indeed fixed the issue. Very nice to see it being addressed this quickly. Great work on `<plastic-image>` !
