### ISSUE TITLE
IntersectionObserver polyfill not working properly

### ISSUE THREAD

**Issue by bramvanderholst** [mlisook/plastic-image#5]
Hi,

The component seems to work perfectly in Chrome!
Safari & Firefox seem to be using an IntersectionObserver polyfill which gives an error. Sadly breaking the functionality entirely;

Safari V10.1 (12603.1.30.0.34)
https://cl.ly/0H34331E2R3f

Firefox V53.0.3 (64-bits)
https://cl.ly/3E2b0R0H3h0y

**Comment by mlisook** [comment]
Thank you for reporting this. 

'll assume that Firefox is on OS X also.

I'll check Github to see if there are reported issues with the polyfill on those browsers.  I'll also turn off minification in the call to polyfill.io to see if I can debug that, though I'm not traveling with my mac today.

**Comment by bramvanderholst** [comment]
Found the problem! 
Since we are using this in a Magento installation we are forced to include `prototype.js`. Apparently this was conflicting with the polyfill.
Updating to a newer version of `prototype.js` fixed the problem.
